#!/bin/bash

#SBATCH --job-name=example-jobname
#SBATCH --partition=example-partition
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --constraint=v100x4
#SBATCH --output=/path/to/logdir/%x.o%j
#SBATCH --error=/path/to/logdir/%x.o%j

msg() { printf "$*\n" >&2; }
die() { msg "!!! $*"; exit 1; }
log() { msg "### $*"; }

hostname

umask 0022

module purge >& /dev/null
module load openmpi/4.1.3-mlnx-gcc
module unload cuda
module load cuda/11.7.1
module load cuda/nccl_2.11.4-1+cuda11.4
module load python/3.10.7
module load cmake/3.17.0

ROOT=/path/to/root # assumed to be run in scripts dir
cd $ROOT

msg "ROOT: $ROOT"

python -m venv venv
source ./venv/bin/activate
[[ -z "$VIRTUAL_ENV" ]] && die "Can't activate venv"

pip install --no-cache-dir --upgrade pip
pip install --no-cache-dir tensorflow
pip install --no-cache-dir torch==1.13.1+cu117 torchaudio==0.13.1+cu117 torchvision==0.14.1+cu117 -f https://download.pytorch.org/whl/torch_stable.html

export HOROVOD_WITH_TENSORFLOW=1
export HOROVOD_WITH_PYTORCH=1
export HOROVOD_NCCL_INCLUDE=/path/to/nccl/include
export HOROVOD_NCCL_LIB=/path/to/nccl/lib
export HOROVOD_GPU_OPERATIONS=NCCL

pip install --no-cache-dir horovod[all-frameworks]
